# Generated by Django 6.0.4 on 2026-05-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('OrderDate', models.DateTimeField()),
                ('ItemName', models.CharField(max_length=255)),
                ('OrderQty', models.IntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DeliveryAddress', models.TextField()),
            ],
        ),
    ]
